services:
  backend:
    platform: linux/amd64
    build: ./project
    image: givemecontent-backend
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db

  db:
    image: postgres:latest

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - backend
