services:
  backend:
    build: ../backend
    image: tofill_backend # TOFILL
    container_name: backend
    command: /app/scripts/dev-runner.sh
    environment:
      - TOFILL_REDIS_URI=redis://redis:6379
      - TOFILL_DATABASE_URI=postgresql://db_user:db_pass@db:5432/db
      - TOFILL_SECRET_KEY=2d396632aac1749beb5c7b05a2f011f0d17605deea94d03910988027d71095fb
      - TOFILL_ADMIN_EMAIL=collinmmeyer@gmail.com
      - TOFILL_ADMIN_PASSWORD=Jkmc15002555
    depends_on:
      - db

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: tofill_router # TOFILL
    container_name: router
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    depends_on:
      - backend

  db:
    image: postgres:16.3
    container_name: db
    volumes:
      - ../dbdata:/var/lib/postgresql/data
    environment:
      # NOTE: THESE MUST BE CHANGED IN PRODUCTION
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    # ports:
    #   - "6379:6379"

  celery:
    build: ../backend
    image: tofill_backend # TOFILL 
    container_name: celery
    environment:
      - TOFILL_REDIS_URI=redis://redis:6379
      - TOFILL_DATABASE_URI=postgresql://db_user:db_pass@db:5432/db
    command: celery -A app.celery.worker.celery worker --loglevel=info -P threads
    depends_on:
      - db
      - redis
