services:
  backend:
    build: ../backend
    image: tofill_backend # TOFILL
    container_name: backend
    ports:
      - 8004:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ../backend:/app
    environment:
      - TOFILL_REDIS_URI=redis://redis:6379
      - TOFILL_DATABASE_URI=postgresql://db_user:db_pass@db:5432/db
    depends_on:
      - db

  nginx:
    image: nginx:1.27.0
    container_name: nginx
    volumes:
    - ./nginx-conf:/etc/nginx/conf.d
    - ../content:/content
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    depends_on:
      - node
      - backend

  db:
    image: postgres:16.3
    container_name: db
    volumes:
      - ../dbdata:/var/lib/postgresql/data
    environment:
      # NOTE: THESE MUST BE CHANGED IN PRODUCTION
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db
    # ports:
    #   - "5432:5432"

  node:
    image: node:22-slim
    container_name: frontend
    volumes:
      - ../frontend:/app
    ports:
      - "8090:3000"
    working_dir: /app
    command: "npm start"

  redis:
    image: redis:7-alpine
    container_name: redis
    # ports:
    #   - "6379:6379"

  celery:
    build: ../backend
    image: tofill_backend # TOFILL 
    container_name: celery
    volumes:
      - ../backend:/app
    environment:
      - TOFILL_REDIS_URI=redis://redis:6379
      - TOFILL_DATABASE_URI=postgresql://db_user:db_pass@db:5432/db
    command: celery -A app.celery.worker.celery worker --loglevel=info -P threads
    depends_on:
      - db
      - redis

  # flower:
  #   build: ../backend
  #   image: tofill_backend # TOFILL
  #   container_name: flower
  #   volumes:
  #     - ../backend:/app
  #   environment:
  #     - TOFILL_REDIS_URI=redis://redis:6379
  #     - TOFILL_DATABASE_URI=postgresql://db_user:db_pass@db:5432/db
  #   command: flower -A app.celery.worker.celery --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - db
  #     - redis
